### ISSUE TITLE
No AllOne device has been found in network

### ISSUE THREAD

**Issue by lucasmenno** [nergal/homeassistant-orvibo-remote#1]
Hello there,

i've stumbled over your magnificent code, that would make my TV smart and automativ, with the Orvibo MagicCube.

But at the start of HA it's showing me this error.

`2022-07-18 20:15:19 WARNING (MainThread) [custom_components.orvibo_remote.remote] No AllOne device has been found in network`

This is my config:

```
orvibo_remote:
remote:
  - platform: orvibo_remote
    host: 192.1.1.144
    name: Orvibo AllOne

smartir:
media_player:
  - platform: smartir
    name: Living TV
    unique_id: living_TV
    device_code: 1100
    controller_data: remote.orvibo_remote_xxxxxxxxxxxx
```

Whats failing there?
